version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aitubet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ../backend  # Убедитесь, что этот путь правильный
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: aitubet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend  # Путь к директории с фронтендом
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html  # Папка с билдом React
    depends_on:
      - app  # Правильно указываем зависимость от бекенда
    networks:
      - narakhate

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html  # Папка с билдом фронтенда
    ports:
      - "80:80"
    depends_on:
      - frontend  # nginx зависит от фронтенда, чтобы сервис был готов

volumes:
  postgres_data:
  
networks:
  narakhate:
    driver: bridge
