version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aitubet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: aitubet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend
    dockerfile: Dockerfile
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../frontend/build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
